### PR TITLE
[IAM] Add AKSK GPG encryption for ``resource/opentelekomcloud_identity_credential_v3``

### LINKED ISSUE #1786: identity_credential_v3: Please don't display and store secret keys in plain text
# Terraform provider version

```
$ terraform version
Terraform v1.2.3
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.29.7
$ 
```

# Affected Resource(s)

- opentelekomcloud_identity_credential_v3

# Terraform Configuration Files

Config is irrelevant, but here's the statefile content instead:

```hcl
$ terraform state show module.iam.opentelekomcloud_identity_credential_v3.this[\"terraform\"]
# module.iam.opentelekomcloud_identity_credential_v3.this["terraform"]:
resource "opentelekomcloud_identity_credential_v3" "this" {
    access        = "YXANNHIEDRWARA0JRN7H"
    create_time   = "2022-06-29T13:02:56.100960Z"
    description   = "Managed by Terraform"
    id            = "YXANNHIEDRWARA0JRN7H"
    last_use_time = "2022-06-29T13:02:56.100960Z"
    secret        = "qdp0j253r5R6aQuHAr0cXaMwAQjOC7hVPD2vZQcF"
    status        = "active"
    user_id       = "1beb89d4b97645509ddf8ac9dc410c17"
}
$
```

# Debug Output/Panic Output

# Steps to Reproduce

1. `terraform state show`

# Expected Behavior

The access_key should not be displayed or stored in plain text, the secret_key must not be displayed or stored in plain text. This is only acceptable during the actual creation time, but not afterwards.
Usually, such fields are supposed to be write-only. Secrets like keys and passwords should not be stored in any backend in plain text anyway, so I wonder from where the provider gets this information during a refresh in the first place? I am a bit worried that this may hint at the major security issue in the backend.

# Actual Behavior

Keys are displayed and saved in the statefile in plain text.

# Important Factoids

When creating an empty resource, and importing an existing user with configured keys, the secret keys are not displayed or stored but treated as nonexistent. Here, the behaviour is correct. Phew.

# References

### PR DESCRIPTION
**Pull request by vladimirvshivkov**
## Summary of the Pull Request
Added GPG encryption for SK secret 

## PR Checklist

* [x] Closes #1786
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.
* [x] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccIdentityV3Credential_basic
--- PASS: TestAccIdentityV3Credential_basic (72.70s)
PASS

Process finished with the exit code 0
```

### CODE REVIEW

File: opentelekomcloud/acceptance/iam/resource_opentelekomcloud_identity_credential_v3_test.go [hunk 1]
```diff
@@ -84,6 +83,7 @@ const (
 	testAccIdentityV3CredentialBasic = `
 resource opentelekomcloud_identity_credential_v3 aksk {
   description = "This is one and unique test AK/SK"
+  pgp_key = "mDMEYs6CMxYJKwYBBAHaRw8BAQdAoF5tLs+wvwvF+A5+mAfdGLrwz3bKdKsUA3iuxQcDUZe0JFZsYWRpbWlyIFZzaGl2a292IDxlbnJyb3VAZ21haWwuY29tPoiZBBMWCgBBFiEEDdv9KvPC2UDkSDiCKWyGs27oaG0FAmLOgjMCGwMFCQPCZwAFCwkIBwICIgIGFQoJCAsCBBYCAwECHgcCF4AACgkQKWyGs27oaG1VKgD8CBsP+kSZsuVXsa+OV1l3bOu1Ql1Ep7iTljk6ih+AIUUBAMIt2Xbm4UjN1RW2Z6lOOJqiMTDKZQ3y37bXdC74UKYOuDgEYs6CMxIKKwYBBAGXVQEFAQEHQE8bDiDqHGlFvwadjLXQ/FSYCWt4Hk7uOAoAdRsR+L8pAwEIB4h+BBgWCgAmFiEEDdv9KvPC2UDkSDiCKWyGs27oaG0FAmLOgjMCGwwFCQPCZwAACgkQKWyGs27oaG0FpQEApm+XVsFSaWA/cfoJadrWQwZzG3+Ifnbw/+yWk9FTxZIA/1FTrsAp/5ajz5O+knRQp6gop1lToK1HzFVgQa12gCQL"
```
Comment (anton-sidelnikov) [inline opentelekomcloud/acceptance/iam/resource_opentelekomcloud_identity_credential_v3_test.go:94]: How works keybase? can you add some test for example?

**Review by anton-sidelnikov — CHANGES_REQUESTED** [review]

File: opentelekomcloud/acceptance/iam/resource_opentelekomcloud_identity_credential_v3_test.go (hunk 1 above)
Comment (vladimirvshivkov) [reply opentelekomcloud/acceptance/iam/resource_opentelekomcloud_identity_credential_v3_test.go:94]: this is hardly automately testable, I will attach terraform hcl that I used to test:
```
resource opentelekomcloud_identity_credential_v3 aksk {
  description = "This is one and unique test AK/SK"
  pgp_key = "keybase:enrrou"
}

output "encrypted_secret" {
  value = "${opentelekomcloud_identity_credential_v3.aksk.secret}"  
}
``` 

gives next output:
```
terraform apply
╷
│ Warning: Provider development overrides are in effect
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # opentelekomcloud_identity_credential_v3.aksk will be created
  + resource "opentelekomcloud_identity_credential_v3" "aksk" {
      + access          = (sensitive value)
      + create_time     = (known after apply)
      + description     = "This is one and unique test AK/SK"
      + id              = (known after apply)
      + key_fingerprint = (known after apply)
      + last_use_time   = (known after apply)
      + pgp_key         = "keybase:enrrou"
      + secret          = (known after apply)
      + status          = (known after apply)
      + user_id         = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + encrypted_secret = (known after apply)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

opentelekomcloud_identity_credential_v3.aksk: Creating...
opentelekomcloud_identity_credential_v3.aksk: Creation complete after 2s [id=JKOXFCBLZ9DGYUEFH37M]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

encrypted_secret = "wcFMA+B3lb4MZcBWARAAXSeaKG+JSHCOkyCrh6e0T5eRtbq4waB5waCaa81VXbgdr3+b+uaVr1ssNZ5VfJCtdM24CC1zpbEmVla7Zsjjk4ikxO3d0Y13MtKYEJ36hq4sABERnn1W3RLIAwH1e15DpVY7qMp1/Mu04MGoKnysNfGg4aCPhUycOHuxdIY0snmPVhKXn9wdqh9ERQCVrouu4ZszCah7A+yniB1/lOdtgwdjoaqhsqd50snPRVq6Ri1qIn487LdYCxtyjoOVHu9N8XALtZljHOnBrmXnAveyhiLHRlhcHmV93fm6Vf6m6bIFVVrIVAhT6JWaIGTduvru2Fh4Hy11CYyG+LlcK1lcIYbsND2jKEDbhXg/VamphYWk8r0MfxAQH30DvMQQIUCQExTCcX5rGJBWKit5pJomQQREcsaLCE9yEpNnKIvQq0eHKCgjrRisc8riZeWBDEUgU8MrErMii5pBfX8uWzhYtjbuQrhX/vzkS9K391dc7G1nENlETg4DhVtCGDHqkbDaD+S/LPSKg0Y0ivJQPUrCQ3z4blAbyny/Fw+8ystIalfYIw/h4+ODaOK18mv7CW+G5cKihOdnxPw6l9XQV0F2DyVSfx3aqSH4AdGTiC+JiuVeV/lftoxEpH7GfZ2EhdwKuR0x29DuliVCnSkovMhHyX/8qsoCM47ZZfTF7wO1GEfS4AHksba4LYMpDkezperFudjsxuHM6OB84KfhrTDgkOK42qIZ4IXlKttXjMXyd/+DiSzOn6gGYpV/jucqvyQiIML3qGARAbngP+M0AolmXFWsTeDN5FHKS9r0KqcDNpPy407WiQHiOXr4i+E8EQA="
```

**Review by anton-sidelnikov — DISMISSED** [review]

File: opentelekomcloud/acceptance/iam/resource_opentelekomcloud_identity_credential_v3_test.go (hunk 1 above)
Comment (vladimirvshivkov) [reply opentelekomcloud/acceptance/iam/resource_opentelekomcloud_identity_credential_v3_test.go:94]: added test just for you)

**Review by anton-sidelnikov — APPROVED** [review]
