### PR TITLE
Fix ECS tags-tag confusion

### LINKED ISSUE #547: [BugFix] Tag attribute for ecs
Hi there,

Please consider renaming the `tag`-attribute for ECS creation to `tags` as used in other resources.

### Terraform Version
Terraform v0.12.26
+ provider.ignition v1.2.1
+ provider.opentelekomcloud v1.18.0
+ provider.random v2.2.1

### Affected Resource(s)
https://www.terraform.io/docs/providers/opentelekomcloud/r/compute_instance_v2.html

### Expected Behavior
I expect the attribute to be `tags` as seen in references below.

### Actual Behavior
Attribute to set tags is `tag`

### References
https://www.terraform.io/docs/providers/opentelekomcloud/r/obs_bucket.html
https://www.terraform.io/docs/providers/opentelekomcloud/r/vpc_subnet_v1.html

### PR DESCRIPTION
**Pull request by lego963**
Fix: #547

### CODE REVIEW

File: opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go [hunk 1]
```diff
@@ -351,20 +350,7 @@ func resourceComputeInstanceV2() *schema.Resource {
...
-				ConflictsWith: []string{"tag"},
-				Deprecated:    "Use field tag instead",
-			},
-			"tag": {
-				Type:          schema.TypeMap,
-				Optional:      true,
-				ConflictsWith: []string{"tags"},
-				ValidateFunc:  validateECSTagValue,
-			},
+			"tags": tagsSchema(),
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go]: This is breaking compatibility. `tag` should be deprecated first

**Review by outcatcher — CHANGES_REQUESTED** [review]

File: opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go (hunk 1 above)
Comment (outcatcher) [reply opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go]: See https://www.terraform.io/docs/extend/best-practices/deprecations.html#provider-attribute-rename

**Comment by outcatcher** [comment]
Please move fix of website-test to another PR

File: opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go [hunk 2]
```diff
@@ -351,19 +349,12 @@ func resourceComputeInstanceV2() *schema.Resource {
...
-				ConflictsWith: []string{"tag"},
-				Deprecated:    "Use field tag instead",
-			},
+			"tags": tagsSchema(),
 			"tag": {
 				Type:          schema.TypeMap,
 				Optional:      true,
 				ConflictsWith: []string{"tags"},
-				ValidateFunc:  validateECSTagValue,
+				Deprecated:    "Use field tags instead",
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go:363]: We should not remove `ValidateFunc`

File: opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go [hunk 3]
```diff
@@ -533,14 +513,22 @@ func resourceComputeInstanceV2Create(d *schema.ResourceData, meta interface{}) e
...
-		log.Printf("[DEBUG] Setting tag(key/value): %v", tagmap)
-		err = setTagForInstance(d, meta, server.ID, tagmap)
+	if hasFilledOpt(d, "tags") {
+		tagsMap := d.Get("tags").(map[string]interface{})
+		log.Printf("[DEBUG] Setting tag(key/value): %v", tagsMap)
+		err = setTagForInstance(d, meta, server.ID, tagsMap)
+		if err != nil {
+			log.Printf("[WARN] Error setting tag(key/value) of instance:%s, err=%s", server.ID, err)
+		}
+	} else if hasFilledOpt(d, "tag") {
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go:525]: Those two blocks are mostly equal

File: opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go [hunk 4]
```diff
@@ -658,97 +646,44 @@ func resourceComputeInstanceV2Read(d *schema.ResourceData, meta interface{}) err
...
+		for _, val := range ecsTagsList.Tags {
+			tagsMap[val.Key] = val.Value
 		}
-		if err := d.Set("tag", tagmap); err != nil {
+		if err := d.Set("tags", tagsMap); err != nil {
 			return fmt.Errorf("[DEBUG] Error saving tag to state for OpenTelekomCloud instance (%s): %s", d.Id(), err)
 		}
-	} else if _, ok := d.GetOk("tags"); ok {
-		taglist, err := GetServerTags(computeClient, d.Id())
+	} else if _, ok := d.GetOk("tag"); ok {
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go:660]: Those blocks are almost equal

File: opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go [hunk 5]
```diff
@@ -910,22 +845,33 @@ func resourceComputeInstanceV2Update(d *schema.ResourceData, meta interface{}) e
...
+			if deleteTags.Err != nil {
+				return fmt.Errorf("Error updating OpenTelekomCloud instance tags: %s", deleteTags.Err)
 			}
-		} else {
-			_, err := CreateServerTags(computeClient, d.Id(), taglist)
-			if err != nil {
-				return fmt.Errorf("Error creating tags for instance (%s): %s", d.Id(), err)
+		}
+
+		if hasFilledOpt(d, "tags") {
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go]: It seems this will fail in case `tags` are removed from the instance

**Review by outcatcher — CHANGES_REQUESTED** [review]

File: opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go [hunk 6]
```diff
@@ -533,14 +514,23 @@ func resourceComputeInstanceV2Create(d *schema.ResourceData, meta interface{}) e
...
-		if err != nil {
-			log.Printf("[WARN] Error setting tag(key/value) of instance:%s, err=%s", server.ID, err)
+	var tagParamName string
+	if hasFilledOpt(d, "tags") {
+		tagParamName = "tags"
+	} else if hasFilledOpt(d, "tag") {
+		tagParamName = "tag"
+	}
+	if tagParamName != "" {
+		tagsMap := d.Get("tags").(map[string]interface{})
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_compute_instance_v2.go]: Should be `d.Get(tagParamName)`

**Review by outcatcher — CHANGES_REQUESTED** [review]

**Review by outcatcher — APPROVED** [review]
