### PR TITLE
[CBR] Add "Tag" to the CBR.

### LINKED ISSUE #1598: CBR - 2nd tag not applied
# Terraform provider version
1.27.2

# Affected Resource(s)
opentelekomcloud_cbr_vault_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_cbr_vault_v3" "vault" {
  name              = var.vault_name
  description       = "CBR vault for host server backups"
  backup_policy_id  = opentelekomcloud_cbr_policy_v3.policy.id
  auto_expand       = true
  tags              ={ env = local.environment_name, terraform_managed = "yes" }
```

# Debug Output/Panic Output

# Steps to Reproduce
1. Resource is applied 
2. No error
3. In OTC, the 2nd tag is not visible at vault resource
4. Re-Applying the resource shows, that the 2nd tag is missing and wants to get applied

# Expected Behavior
Both tags should be applied to the vault resource

# Actual Behavior
Only the 1st tag is applied

# Important Factoids

# References

### PR DESCRIPTION
**Pull request by Aloento**
## Summary of the Pull Request

Add "Tag" to the currently available features.

## PR Checklist

* [x] Refers to: #1598
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.
* [x] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccCBRVaultV3_basic
=== PAUSE TestAccCBRVaultV3_basic
=== CONT  TestAccCBRVaultV3_basic
--- PASS: TestAccCBRVaultV3_basic (183.41s)
PASS
```

### CODE REVIEW

File: opentelekomcloud/common/validators.go [hunk 1]
```diff
@@ -260,35 +260,6 @@ func ValidateAntiDdosAppTypeID(v interface{}, k string) (ws []string, errors []e
 	return
 }
 
-func ValidateTags(v interface{}, k string) (ws []string, errors []error) {
```
Comment (Aloento) [inline opentelekomcloud/common/validators.go]: Remove the validation because there are very many rules for tag, and different rules for different situations, so it is best to just leave it to the server to validate.

File: opentelekomcloud/common/tags.go [hunk 2]
```diff
@@ -9,9 +9,9 @@ import (
 // TagsSchema returns the schema to use for tags.
 func TagsSchema() *schema.Schema {
 	return &schema.Schema{
-		Type:         schema.TypeMap,
-		Optional:     true,
-		ValidateFunc: ValidateTags,
+		Type:     schema.TypeMap,
+		Optional: true,
+		Elem:     &schema.Schema{Type: schema.TypeString},
```
Comment (artem-lifshits) [inline opentelekomcloud/common/tags.go]: Most of the tag validation use common standard validation rules, some of them like CBR vaults may be different.

With this validation terraform can tell that configuration is invalid without launching configuration itself, which saves a lot of time in case configuration has lots and lots of resources.

That's why we need validation inside schema.
Please restore all validation fields.

**Review by artem-lifshits — CHANGES_REQUESTED** [review]
Release notes needed.

You can add them via "reno new ...", please check `releasenotes` for examples.

File: opentelekomcloud/common/tags.go (hunk 2 above)
Comment (Aloento) [reply opentelekomcloud/common/tags.go]: I've found a few cases that don't pass the verification, but I've restored them as you requested.

**Comment by Aloento** [comment]
I cannot pass most of the tests. it seems like:
```
=== RUN   TestAccCssClusterV1_basic
=== PAUSE TestAccCssClusterV1_basic
=== CONT  TestAccCssClusterV1_basic
    resource_opentelekomcloud_css_cluster_v1_test.go:25: Step 1/2 error: Error running pre-apply refresh: exit status 1
        
        Error: no matching subnet found. Please change your search criteria and try again
        
          with data.opentelekomcloud_vpc_subnet_v1.shared_subnet,
          on terraform_plugin_test.tf line 9, in data "opentelekomcloud_vpc_subnet_v1" "shared_subnet":
           9: data "opentelekomcloud_vpc_subnet_v1" "shared_subnet"  {
        
--- FAIL: TestAccCssClusterV1_basic (11.72s)
```

So it would be nice if someone could help run the tests.

**Comment by anton-sidelnikov** [comment]
> I cannot pass most of the tests. it seems like:
> 
> ```
> === RUN   TestAccCssClusterV1_basic
> === PAUSE TestAccCssClusterV1_basic
> === CONT  TestAccCssClusterV1_basic
>     resource_opentelekomcloud_css_cluster_v1_test.go:25: Step 1/2 error: Error running pre-apply refresh: exit status 1
>         
>         Error: no matching subnet found. Please change your search criteria and try again
>         
>           with data.opentelekomcloud_vpc_subnet_v1.shared_subnet,
>           on terraform_plugin_test.tf line 9, in data "opentelekomcloud_vpc_subnet_v1" "shared_subnet":
>            9: data "opentelekomcloud_vpc_subnet_v1" "shared_subnet"  {
>         
> --- FAIL: TestAccCssClusterV1_basic (11.72s)
> ```
> 
> So it would be nice if someone could help run the tests.

subnet should exist in your project, and env variable should point to it OS_SUBNET_NAME=subnet

**Comment by anton-sidelnikov** [comment]
Also i prefer to revert all validations and keep only cbr resource in this pr

**Comment by anton-sidelnikov** [comment]
@Aloento and if you adding some parameters they should be present in test config
image

**Comment by Aloento** [comment]
```
=== RUN   TestAccCBRVaultV3_basic
=== PAUSE TestAccCBRVaultV3_basic
=== CONT  TestAccCBRVaultV3_basic
--- PASS: TestAccCBRVaultV3_basic (93.72s)
PASS
```

File: opentelekomcloud/services/bms/resource_opentelekomcloud_compute_bms_server_v2.go [hunk 3]
```diff
@@ -189,11 +189,7 @@ func ResourceComputeBMSInstanceV2() *schema.Resource {
 				ForceNew: true,
 				Computed: true,
 			},
-			"tags": {
```
Comment (anton-sidelnikov) [inline opentelekomcloud/services/bms/resource_opentelekomcloud_compute_bms_server_v2.go]: please not in this pr

File: opentelekomcloud/services/cbr/resource_opentelekomcloud_cbr_vault_v3.go [hunk 4]
```diff
@@ -216,12 +216,7 @@ func ResourceCBRVaultV3() *schema.Resource {
 				Type:     schema.TypeString,
 				Optional: true,
 			},
-			"tags": {
-				Type:         schema.TypeMap,
-				Optional:     true,
-				ForceNew:     true,
-				ValidateFunc: common.ValidateTags,
```
Comment (anton-sidelnikov) [inline opentelekomcloud/services/cbr/resource_opentelekomcloud_cbr_vault_v3.go:223]: revert validation for this time, it's a bad idea to left it to the server

File: opentelekomcloud/services/css/resource_opentelekomcloud_css_cluster_v1.go [hunk 5]
```diff
@@ -161,12 +161,7 @@ func ResourceCssClusterV1() *schema.Resource {
 					},
 				},
 			},
-			"tags": {
```
Comment (anton-sidelnikov) [inline opentelekomcloud/services/css/resource_opentelekomcloud_css_cluster_v1.go]: please not in this pr

File: opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_listener_v3.go [hunk 6]
```diff
@@ -144,12 +144,7 @@ func ResourceListenerV3() *schema.Resource {
 					},
 				},
 			},
-			"tags": {
```
Comment (anton-sidelnikov) [inline opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_listener_v3.go]: please not in this pr

File: opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_loadbalancer_v3.go [hunk 7]
```diff
@@ -155,12 +155,7 @@ func ResourceLoadBalancerV3() *schema.Resource {
 					},
 				},
 			},
-			"tags": {
```
Comment (anton-sidelnikov) [inline opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_loadbalancer_v3.go]: please not in this pr

File: opentelekomcloud/services/rds/resource_opentelekomcloud_rds_instance_v1.go [hunk 8]
```diff
@@ -188,11 +188,8 @@ func ResourceRdsInstance() *schema.Resource {
 						},
 					}},
 			},
-			"tag": {
```
Comment (anton-sidelnikov) [inline opentelekomcloud/services/rds/resource_opentelekomcloud_rds_instance_v1.go]: please not in this pr

File: opentelekomcloud/services/smn/resource_opentelekomcloud_smn_topic_v2.go [hunk 9]
```diff
@@ -39,6 +39,7 @@ func ResourceTopic() *schema.Resource {
 				Optional: true,
 				ForceNew: false,
 			},
+			"tags": common.TagsSchema(),
```
Comment (anton-sidelnikov) [inline opentelekomcloud/services/smn/resource_opentelekomcloud_smn_topic_v2.go]: please not in this pr, test failed

**Review by anton-sidelnikov — CHANGES_REQUESTED** [review]

File: opentelekomcloud/services/cbr/resource_opentelekomcloud_cbr_vault_v3.go (hunk 4 above)
Comment (Aloento) [reply opentelekomcloud/services/cbr/resource_opentelekomcloud_cbr_vault_v3.go:223]: common.TagsSchema() contain the ValidateFunc

**Review by anton-sidelnikov — DISMISSED** [review]

File: opentelekomcloud/services/cbr/resource_opentelekomcloud_cbr_vault_v3.go [hunk 10]
```diff
@@ -371,6 +365,10 @@ func resourceCBRVaultV3Create(ctx context.Context, d *schema.ResourceData, meta
 		}
 	}
 
+	if err := common.UpdateResourceTags(client, d, "vault", d.Id()); err != nil {
```
Comment (artem-lifshits) [inline opentelekomcloud/services/cbr/resource_opentelekomcloud_cbr_vault_v3.go]: Please manage tags along with vault creation, there's no need to send an extra request

File: opentelekomcloud/acceptance/cbr/resource_opentelekomcloud_cbr_vault_v3_test.go [hunk 11]
```diff
@@ -263,6 +263,11 @@ resource "opentelekomcloud_cbr_vault_v3" "vault" {
     period_num    = 2
   }
```
Comment (artem-lifshits) [inline opentelekomcloud/acceptance/cbr/resource_opentelekomcloud_cbr_vault_v3_test.go:272]: Initial ticket issue was that when tags were updated the resource had to be completely recreated.

So please add acceptance tests with at least 2 steps where different tags are applied. Tag checks are needed along with check that resource remains the same (this can be done by checking vault id).

It can be as simple as possible, we only have to check tags management in this test.

**Review by artem-lifshits — CHANGES_REQUESTED** [review]

File: opentelekomcloud/acceptance/cbr/resource_opentelekomcloud_cbr_vault_v3_test.go (hunk 11 above)
Comment (Aloento) [reply opentelekomcloud/acceptance/cbr/resource_opentelekomcloud_cbr_vault_v3_test.go:272]: Sorry, I am not very familiar with how I should write the acceptance test, can you help me?
And I think the update has actually been executed successfully, as verified in the previous call to UpdateResourceTags.
So I don't think it makes much sense to write another test.

Comment (artem-lifshits) [reply opentelekomcloud/acceptance/cbr/resource_opentelekomcloud_cbr_vault_v3_test.go:272]: Update will be executed successfully but you're sending 2 requests on resource creation while it can be done in one step.

**Review by anton-sidelnikov — DISMISSED** [review]

**Comment by Aloento** [comment]
=== RUN   TestAccCBRVaultV3_basic
=== PAUSE TestAccCBRVaultV3_basic
=== CONT  TestAccCBRVaultV3_basic
--- PASS: TestAccCBRVaultV3_basic (113.27s)
PASS

**Review by anton-sidelnikov — DISMISSED** [review]

File: releasenotes/notes/add-tag-to-the-cbr-cef536d4cfb769d7.yaml [hunk 12]
```diff
@@ -0,0 +1,4 @@
+---
+fixes:
+  - |
+    **[CBR]** Add Tag to the CBR (`#1598 <https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1598>`_)
```
Comment (lego963) [inline releasenotes/notes/add-tag-to-the-cbr-cef536d4cfb769d7.yaml]: it is not completely clear what was done and where and fix please #1598 to #1833 
here we point to PR, not issue 

PS:
I mean smth like this
```
enhancement
Add possibility to ``Update`` ``tags`` in ``resource/opentelekomcloud_cbr_vault_v3``
```

**Comment by lego963** [comment]
@Aloento you almost didn't fully understand me
I meant that you have to move  your change from `fixes` to `enhanc` block
there is template for reno with this block
`reno --from-template releasenotes/template.yaml  new  <reno_name>`

**Review by lego963 — APPROVED** [review]

**Review by artem-lifshits — APPROVED** [review]

**Review by anton-sidelnikov — APPROVED** [review]
