### PR TITLE
[NAT] Fix `nat_snat_rule_v2` reading of `source_type` field

### LINKED ISSUE #1628: Snat Rule Type error
# Terraform provider version

```
provider registry.terraform.io/hashicorp/external v2.2.0
provider registry.terraform.io/hashicorp/local v2.1.0
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.27.4
```

# Affected Resource(s)

- opentelekomcloud_nat_snat_rule_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_nat_snat_rule_v2" "snat" {
  nat_gateway_id = opentelekomcloud_nat_gateway_v2.nat.id
  floating_ip_id = opentelekomcloud_networking_floatingip_v2.fip_1.id
  network_id     = module.vpc.subnet_network_id
  source_type    = 0
}
```

# Debug Output/Panic Output

```
╷
│ Error: error creating SNAT Rule: json: cannot unmarshal number into Go struct field SnatRule.source_type of type string
│
│   with opentelekomcloud_nat_snat_rule_v2.snat,
│   on main.tf line 69, in resource "opentelekomcloud_nat_snat_rule_v2" "snat":
│   69: resource "opentelekomcloud_nat_snat_rule_v2" "snat" {
│
╵
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

1. The documentation states that the type is an Integer.
2. If it is a string, the snat rule should not be created.

# Actual Behavior

1. The type error occurs
2. The Snatrule is created anyway, despite of the error, but not part of the terraform state afterwards.
3. Changing it to `source_type = "0"` results in the same error

# Important factoids
1. Environment is NL

# References

https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/nat_snat_rule_v2

### PR DESCRIPTION
**Pull request by lego963**
## Summary of the Pull Request
Fix reading of `source_type` field in `resource/opentelekomcloud_nat_snat_rule_v2`
Fixes: #1628

## PR Checklist

* [x] Refers to: #1628
* [x] Tests added/passed.
* [x] Release notes added.

## Acceptance Steps Performed

`EU-DE`
```
=== RUN   TestAccNatSnatRule_basic
--- PASS: TestAccNatSnatRule_basic (98.99s)
PASS


Process finished with the exit code 0
```
`EU-NL`
```
=== RUN   TestAccNatSnatRule_basic
--- PASS: TestAccNatSnatRule_basic (101.74s)
PASS


Process finished with the exit code 0
```

### CODE REVIEW

File: opentelekomcloud/services/nat/resource_opentelekomcloud_nat_snat_rule_v2.go [hunk 1]
```diff
@@ -137,13 +136,11 @@ func resourceNatSnatRuleV2Read(_ context.Context, d *schema.ResourceData, meta i
 		d.Set("cidr", snatRule.Cidr),
 		d.Set("region", config.GetRegion(d)),
 	)
-	sourceType, err := strconv.Atoi(snatRule.SourceType)
-	if err != nil {
-		return fmterr.Errorf("error converting `source_type`: %w", err)
+	if sourceType, ok := snatRule.SourceType.(int); ok {
+		mErr = multierror.Append(mErr,
+			d.Set("source_type", sourceType),
+		)
```
Comment (outcatcher) [inline opentelekomcloud/services/nat/resource_opentelekomcloud_nat_snat_rule_v2.go]: Only `int` source type is handled in this case

**Review by outcatcher — APPROVED** [review]
