### PR TITLE
[ECS] Fix issue with multiple networks

### LINKED ISSUE #1039: [ECS][IMPORT] opentelekomcloud_compute_instance_v2 seams to not work with multiple Subnet in VPC
## Version
```bash
$ terraform --version
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.23.9
```
Import doesnt work with having a SINGLE interface on the ECS but having multiple VPC-Subnet in the VPC where I try to import it.

## Network
I have somethink like this as Network:
```hcl
resource "opentelekomcloud_vpc_v1" "vpc_v1" {
  name = var.vpc_name
  cidr = var.vpc_cidr
}

resource "opentelekomcloud_vpc_subnet_v1" "subnet_1" {
  name   = var.subnet_name_1
  cidr   = var.subnet_cidr_1
  vpc_id = opentelekomcloud_vpc_v1.vpc_v1.id

  gateway_ip    = var.subnet_gateway_ip_1
  ntp_addresses = "10.100.0.33,10.100.0.34"
}

resource "opentelekomcloud_vpc_subnet_v1" "subnet_2" {
  name   = var.subnet_name_2
  cidr   = var.subnet_cidr_2
  vpc_id = opentelekomcloud_vpc_v1.vpc_v1.id

  gateway_ip    = var.subnet_gateway_ip_2
  ntp_addresses = "10.100.0.33,10.100.0.34"
}

resource "opentelekomcloud_vpc_subnet_v1" "subnet_3" {
  name   = var.subnet_name_3
  cidr   = var.subnet_cidr_3
  vpc_id = opentelekomcloud_vpc_v1.vpc_v1.id

  gateway_ip    = var.subnet_gateway_ip_3
  ntp_addresses = "10.100.0.33,10.100.0.34"
}
```
## ECS Instance
The instance looks like:
I double checked that the Instances is (for real) only connected to ONE network...
```hcl
resource "opentelekomcloud_compute_instance_v2" "ecs_instance" {
  name      = "boot-from-volume"
  flavor_id = var.flavor_id
  key_pair  = var.key_pair
  image_id  = var.image_id

  network {
    id        = opentelekomcloud_vpc_subnet_v1.subnet_2.id
    fixed_ip_v4 = "<fixed_ip_v4>"
  }

}
```

## Import try
@outcatcher 
```bash
$ terraform import opentelekomcloud_compute_instance_v2.ecs_instance xxxxxxxxxxxxxxx-yyyyyyyyyyyyyyy
opentelekomcloud_compute_instance_v2.ecs_instance: Importing from ID "xxxxxxxxxxxxxxx-yyyyyyyyyyyyyyy"...
opentelekomcloud_compute_instance_v2.ecs_instance: Import prepared!
  Prepared opentelekomcloud_compute_instance_v2 for import
opentelekomcloud_compute_instance_v2.ecs_instance: Refreshing state... [id=xxxxxxxxxxxxxxx-yyyyyyyyyyyyyyy]

Error: Error trying to get network information from the Network API: More than one network found for name <ID of the VPC>
```
## API
API Response is like:
```
"networks": [
{
  "admin_state_up": true,
  "availability_zone_hints": [],
  "availability_zones": [
    "eu-de-01",
    "eu-de-02",
    "eu-de-03"
  ],
  "created_at": "2021-04-27T13:32:35",
  "dns_domain": "eu-de.compute.internal.",
  "id": "xxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyy",
  "name": "zzzzzzzzzzzzzzyyyyyyyyyyyyyyyyyy",
  "port_security_enabled": true,
  "project_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "provider:network_type": "vxlan",
  "router:external": false,
  "shared": false,
  "status": "ACTIVE",
  "subnets": [
    "zzzzzzzzzzzzzzzzzzzzzzz"
  ],
  "tenant_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "updated_at": "2021-04-27T13:32:35"
},
{
  "admin_state_up": true,
  "availability_zone_hints": [],
  "availability_zones": [
    "eu-de-01",
    "eu-de-02",
    "eu-de-03"
  ],
  "created_at": "2021-04-27T13:31:13",
  "dns_domain": "eu-de.compute.internal.",
  "id": "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
  "name": "zzzzzzzzzzzzzzyyyyyyyyyyyyyyyyyy",
  "port_security_enabled": true,
  "project_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "provider:network_type": "vxlan",
  "router:external": false,
  "shared": false,
  "status": "ACTIVE",
  "subnets": [
    "gggggggggggggggggggggggggggggggggggggggg"
  ],
  "tenant_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "updated_at": "2021-04-27T13:31:13"
},
{
  "admin_state_up": true,
  "availability_zone_hints": [],
  "availability_zones": [
    "eu-de-01",
    "eu-de-02",
    "eu-de-03"
  ],
  "created_at": "2020-10-15T14:50:35",
  "dns_domain": "eu-de.compute.internal.",
  "id": "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
  "name": "zzzzzzzzzzzzzzyyyyyyyyyyyyyyyyyy",
  "port_security_enabled": true,
  "project_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "provider:network_type": "vxlan",
  "router:external": false,
  "shared": false,
  "status": "ACTIVE",
  "subnets": [
    "fffffffffffffffffffffffffffffffffff"
  ],
  "tenant_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "updated_at": "2020-10-15T14:50:35"
}

etworks_links": [
{
  "href": "https://vpc.eu-de.otc.t-systems.com/v2.0/networks?limit=2000\u0026shared=False\u0026router:external=False\u0026name=zzzzzzzzzzzzzzyyyyyyyyyyyyyyyyyy\u0026provider:network_type=vxlan\u0026provider:network_type=geneve\u0026status=ACTIVE\u0026marker=xxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyy\u0026page_reverse=true",
  "rel": "previous"
}
2021-04-30T05:51:22.613+0200 [DEBUG] provider.terraform-provider-opentelekomcloud_v1.23.9:   ]

```
_Originally posted by @Moep90 in https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1023#issuecomment-829789132_

### PR DESCRIPTION
**Pull request by lego963**
## Summary of the Pull Request
Fix issue with reading networks in `resource/opentelekomcloud_compute_instance_v2`
Fixes: #1039

## PR Checklist

* [x] Refers to: #1039
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed

```
=== RUN   TestAccComputeV2Instance_basic
--- PASS: TestAccComputeV2Instance_basic (140.33s)
=== RUN   TestAccComputeV2Instance_multiSecgroup
--- PASS: TestAccComputeV2Instance_multiSecgroup (149.64s)
=== RUN   TestAccComputeV2Instance_bootFromImage
--- PASS: TestAccComputeV2Instance_bootFromImage (79.78s)
=== RUN   TestAccComputeV2Instance_bootFromVolume
--- PASS: TestAccComputeV2Instance_bootFromVolume (78.77s)
=== RUN   TestAccComputeV2Instance_changeFixedIP
--- PASS: TestAccComputeV2Instance_changeFixedIP (80.90s)
=== RUN   TestAccComputeV2Instance_bootFromVolumeVolume
--- PASS: TestAccComputeV2Instance_bootFromVolumeVolume (100.41s)
=== RUN   TestAccComputeV2Instance_stopBeforeDestroy
--- PASS: TestAccComputeV2Instance_stopBeforeDestroy (126.18s)
=== RUN   TestAccComputeV2Instance_metadata
--- PASS: TestAccComputeV2Instance_metadata (137.88s)
=== RUN   TestAccComputeV2Instance_timeout
--- PASS: TestAccComputeV2Instance_timeout (87.94s)
=== RUN   TestAccComputeV2Instance_autoRecovery
--- PASS: TestAccComputeV2Instance_autoRecovery (127.58s)
=== RUN   TestAccComputeV2Instance_crazyNICs
--- PASS: TestAccComputeV2Instance_crazyNICs (231.48s)
=== RUN   TestAccComputeV2Instance_initialStateActive
--- PASS: TestAccComputeV2Instance_initialStateActive (215.49s)
=== RUN   TestAccComputeV2Instance_initialStateShutoff
--- PASS: TestAccComputeV2Instance_initialStateShutoff (287.69s)
PASS

Process finished with the exit code 0
```

### CODE REVIEW

File: opentelekomcloud/services/ecs/compute_instance_v2_networking.go [hunk 1]
```diff
@@ -423,24 +420,25 @@ func FlattenInstanceNetworks(
...
+				serverNICs, err := servers.GetNICs(computeClient, server.ID).Extract()
 				if err != nil {
-					log.Printf("[WARN] Error getting default network uuid: %s", err)
-				} else {
-					if v["uuid"] != nil {
-						v["uuid"] = networkInfo["uuid"].(string)
-					} else {
-						log.Printf("[WARN] Could not get default network uuid")
+					return nil, err
+				}
```
Comment (outcatcher) [inline opentelekomcloud/services/ecs/compute_instance_v2_networking.go]: This API call should be done out of all cycles

**Review by outcatcher — CHANGES_REQUESTED** [review]

File: opentelekomcloud/services/ecs/compute_instance_v2_networking.go (hunk 1 above)
Comment (lego963) [reply opentelekomcloud/services/ecs/compute_instance_v2_networking.go]: Done

**Review by outcatcher — APPROVED** [review]
