### PR TITLE
[CSS] Fix potential nil pointer issue

### LINKED ISSUE #1054: [CSS] `checkCssClusterFlavorRestrictions` has potential nil pointer usage
# Terraform Version
Upstream branch

# Affected Resource(s)
- `opentelekomcloud_css_cluster_v1`

# Source
`flavor` can be `nil` if the flavor not found:
```go
	flavor := flavors.FindFlavor(versions, flavors.FilterOpts{
		FlavorName: flavorName,
	})

	if size < flavor.DiskMin || size > flavor.DiskMax {
		return fmt.Errorf("invalid disk size, `%s` support disk from %dGB to %dGB",
			flavorName, flavor.DiskMin, flavor.DiskMax)
	}
```

### PR DESCRIPTION
**Pull request by lego963**
## Summary of the Pull Request

Fix potential nil pointer issue

Fixes: #1054 

## PR Checklist

* [x] Refers to: #1054
* [x] Tests added/passed.

## Acceptance Steps Performed

```
=== RUN   TestAccCssClusterV1_validateDiskandFlavor
--- PASS: TestAccCssClusterV1_validateDiskandFlavor (34.20s)
PASS

Process finished with the exit code 0
```

### CODE REVIEW

File: opentelekomcloud/services/css/resource_opentelekomcloud_css_cluster_v1.go [hunk 1]
```diff
@@ -411,6 +411,9 @@ func checkCssClusterFlavorRestrictions(d *schema.ResourceDiff, meta interface{})
 	flavor := flavors.FindFlavor(versions, flavors.FilterOpts{
 		FlavorName: flavorName,
 	})
+	if flavor == nil {
+		return fmt.Errorf("can't find flavor matching criteria: %s", flavorName)
```
Comment (outcatcher) [inline opentelekomcloud/services/css/resource_opentelekomcloud_css_cluster_v1.go]: `criteria` is not specific, please use `flavor name` instead

**Review by outcatcher — CHANGES_REQUESTED** [review]
Please add acceptance tests

**Review by outcatcher — APPROVED** [review]
