### PR TITLE
[KMS] Add `allow_cancel_deletion` in schema of `kms_key_v1`

### LINKED ISSUE #1804: kms_key_v1: Please check state before trying to create a key
# Terraform provider version

```
Terraform v1.3.0-alpha20220608
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.29.9
```

# Affected Resource(s)

opentelekomcloud_kms_key_v1

# Terraform Configuration Files

```hcl
module "kms" {
  source = "../modules/terraform-opentelekomcloud-kms"

  kms_keys = {
    key1 = { alias = "test" }
    key2 = { alias = "test-2", description = "A test key", is_rotation_enabled = true, rotation_interval = 90 }
  }
}
```

```hcl
resource "opentelekomcloud_kms_key_v1" "this" {
  for_each = var.kms_keys != null ? var.kms_keys : {}

  key_alias = each.value["alias"]
  key_description = each.value["description"]
  realm = each.value["realm"]
  pending_days = each.value["pending_days"]
  is_enabled = each.value["is_enabled"]
  rotation_interval = each.value["rotation_interval"]
  rotation_enabled = each.value["is_rotation_enabled"]
  tags = var.tags
}
```

# Debug Output/Panic Output

```
module.kms.opentelekomcloud_kms_key_v1.this["key2"]: Still creating... [10s elapsed]
module.kms.opentelekomcloud_kms_key_v1.this["key1"]: Still creating... [10s elapsed]
╷
│ Error: error waiting for key (f043636f-79d9-4fc0-9d5d-8f491dc13065) to become ready: unexpected state '4', wanted target '2'. last error: %!s(<nil>)
│ 
│   with module.kms.opentelekomcloud_kms_key_v1.this["key2"],
│   on ../modules/terraform-opentelekomcloud-kms/main.tf line 1, in resource "opentelekomcloud_kms_key_v1" "this":
│    1: resource "opentelekomcloud_kms_key_v1" "this" {
│ 
╵
╷
│ Error: error waiting for key (b6654ceb-3325-4d75-ae91-3e37be5e9538) to become ready: unexpected state '4', wanted target '2'. last error: %!s(<nil>)
│ 
│   with module.kms.opentelekomcloud_kms_key_v1.this["key1"],
│   on ../modules/terraform-opentelekomcloud-kms/main.tf line 1, in resource "opentelekomcloud_kms_key_v1" "this":
│    1: resource "opentelekomcloud_kms_key_v1" "this" {
│ 
```

# Steps to Reproduce

1. `terraform apply`
2. `terraform destroy` 
3. `terraform apply`

# Expected Behavior

After a `destroy`, another `apply` on the same terraform code should work.

# Actual Behavior

During the `destroy`, the kms resource gets removed from the state, even though it still exists in OTC for a minimum of 7 and a maximum of 1096 days. During this period, which in production environments can pretty much effectively feel like "forever",  other `apply`runs will loead into this error since the KMS is within OTC in the state "Pending deletion".

The only workaround on terraform level which I see at the moment would be appending random values to the key_alias to make the keys effectively unique, but this is visible for the customer and thus pretty ugly.

So, to avoid breaking customer's production environment, I see two possibilities:

1) (Preferred) The provider should check if a key already exists, and if the state of the kms key is "Pending deletion" the creation should be skipped and optionally a Warning be generated on stdout. Or any other kind of error handling which seems more appropriate. Other cloud providers like Oracle already implement this in the backend and check this during refresh in the planning stage, so it should somehow be possible here, too I think.

2) The quick & dirty solution which comes to my mind would be the introduction of a display_name and turning the key_alias unique.

# Important Factoids

# References

### PR DESCRIPTION
**Pull request by anton-sidelnikov**
## Summary of the Pull Request
Added ability to canceling the Scheduled Deletion of a CMK

## PR Checklist

* [x] Refers to: #1804 
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.
* [x] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccKmsKeyV1_basic
--- PASS: TestAccKmsKeyV1_basic (83.71s)
=== RUN   TestAccKmsKey_isEnabled
--- PASS: TestAccKmsKey_isEnabled (115.14s)
=== RUN   TestAccKmsKey_rotation
--- PASS: TestAccKmsKey_rotation (50.18s)
=== RUN   TestAccKmsKey_cancelDeletion
--- PASS: TestAccKmsKey_cancelDeletion(51.07s)
PASS

Process finished with the exit code 0
```

### CODE REVIEW

**Review by artem-lifshits — DISMISSED** [review]

File: opentelekomcloud/acceptance/kms/resource_opentelekomcloud_kms_key_v1_test.go [hunk 1]
```diff
@@ -224,3 +246,17 @@ resource "opentelekomcloud_kms_key_v1" "key_1" {
   rotation_interval = 183
 }`, prefix)
 }
+
+func testAccKmsV1Key_desiredState(rName string) string {
+	return fmt.Sprintf(`
+resource "opentelekomcloud_kms_key_v1" "key_1" {
+  key_alias       = "%s"
+  desired_state   = "ENABLED"
```
Comment (vladimirvshivkov) [inline opentelekomcloud/acceptance/kms/resource_opentelekomcloud_kms_key_v1_test.go]: why would you decided to use this way instead of:
`is_enabled = true`?

File: opentelekomcloud/services/kms/resource_opentelekomcloud_kms_key_v1.go [hunk 2]
```diff
@@ -62,6 +61,13 @@ func ResourceKmsKeyV1() *schema.Resource {
 				Type:     schema.TypeString,
 				Computed: true,
 			},
+			"desired_state": {
+				Type:     schema.TypeString,
+				Optional: true,
+				ValidateFunc: validation.StringInSlice([]string{
```
Comment (vladimirvshivkov) [inline opentelekomcloud/services/kms/resource_opentelekomcloud_kms_key_v1.go]: also bool won't require validation

File: opentelekomcloud/services/kms/resource_opentelekomcloud_kms_key_v1.go [hunk 3]
```diff
@@ -142,6 +148,30 @@ func resourceKmsKeyV1Create(ctx context.Context, d *schema.ResourceData, meta in
 	}
 	log.Printf("[INFO] Key ID: %s", key.KeyID)
 
+	if d.Get("desired_state").(string) == "ENABLED" {
```
Comment (vladimirvshivkov) [inline opentelekomcloud/services/kms/resource_opentelekomcloud_kms_key_v1.go]: if is_enabled check the state of key's pending deletion and reenable if required

**Review by vladimirvshivkov — CHANGES_REQUESTED** [review]
desired state its kinda weird arg for terraform's declarative code

File: opentelekomcloud/acceptance/kms/resource_opentelekomcloud_kms_key_v1_test.go (hunk 1 above)
Comment (anton-sidelnikov) [reply opentelekomcloud/acceptance/kms/resource_opentelekomcloud_kms_key_v1_test.go]: this resource already have is_enabled parameter

File: opentelekomcloud/services/kms/resource_opentelekomcloud_kms_key_v1.go (hunk 3 above)
Comment (anton-sidelnikov) [reply opentelekomcloud/services/kms/resource_opentelekomcloud_kms_key_v1.go]: > desired state its kinda weird arg for terraform's declarative code

Yes, desided to rename it allow_cancel_deletion and make it bool

**Review by vladimirvshivkov — APPROVED** [review]
