### PR TITLE
[ECS] Fix creating instance with `image_name`

### LINKED ISSUE #1597: [ECS] Querying Image Details API is discarded
# Description of the enhancement
`ComputeV2` APIs are in `discarded` state https://docs.otc.t-systems.com/en-us/api/ecs/en-us_topic_0065817696.html

# Affected resources:
`resource/opentelekomcloud_compute_instance_v2`

# Reference:
```go
	if imageName := d.Get("image_name").(string); imageName != "" {
		imageId, err := images.IDFromName(client, imageName)
		if err != nil {
			return "", err
		}
		return imageId, nil
	}
```

```
* openstack_compute_instance_v2.ctd-BastionHost-0: Expected HTTP response code [200 204 300] when accessing [GET https://ecs.eu-de.otc.t-systems.com/v2.1/123456/images/detail], but got 504 instead
{"message":"Wait response timeout.","request_id":"b91de15ec91d6eebd4c161c959ac533"}
```

### PR DESCRIPTION
**Pull request by outcatcher**
## Summary of the Pull Request
Move image ID resolution to `IMSv2` from discarded API

Fix #1597

## PR Checklist

* [x] Refers to: #1597
* [x] Tests added/passed.
* [x] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccComputeV2Instance_imageByName
--- PASS: TestAccComputeV2Instance_imageByName (74.64s)
PASS

Process finished with the exit code 0

```

### CODE REVIEW

**Review by lego963 — DISMISSED** [review]

File: opentelekomcloud/services/ims/common.go [hunk 1]
```diff
@@ -5,14 +5,40 @@ import (
...
 )
 
 const (
 	errCreationClient = "error creating OpenTelekomCloud IMSv2 client: %w"
 )
 
+func GetImageByName(d *schema.ResourceData, cfg *cfg.Config, name string) (string, error) {
+	client, err := cfg.ImageV2Client(cfg.GetRegion(d))
+	if err != nil {
+		return "", fmt.Errorf("error crating IMSv2 client: %w", err)
```
Comment (anton-sidelnikov) [inline opentelekomcloud/services/ims/common.go]: creating

**Review by anton-sidelnikov — CHANGES_REQUESTED** [review]

**Review by lego963 — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by lego963 — APPROVED** [review]
