### PR TITLE
[AS] Fix wrong SHA1 calculation

### LINKED ISSUE #1158: [AS] `user_data` is  is broken
# Affected Resource(s)
opentelekomcloud_as_configuration_v1

# Debug Output/Panic Output
```
- user_data       = "da39a3ee5e6b4b0d3255bfef95601890afd80709" -> null
```

This value `da39a3ee5e6b4b0d3255bfef95601890afd80709` should be supressed.

### PR DESCRIPTION
**Pull request by lego963**
## Summary of the Pull Request
Fix wrong SHA1 sum calculation of empty `user_data` in `resource/opentelekomcloud_as_configuration_v1`
Fixes: #1158

## PR Checklist

* [x] Refers to: #1158
* [x] Tests added/passed.
* [x] Schema updated.

## Acceptance Steps Performed

```
=== RUN   TestAccASV1Configuration_basic
--- PASS: TestAccASV1Configuration_basic (32.52s)
=== RUN   TestAccASV1Configuration_publicIP
--- PASS: TestAccASV1Configuration_publicIP (32.31s)
=== RUN   TestAccASV1Configuration_invalidDiskSize
--- PASS: TestAccASV1Configuration_invalidDiskSize (7.46s)
=== RUN   TestAccASV1Configuration_multipleSecurityGroups
--- PASS: TestAccASV1Configuration_multipleSecurityGroups (49.96s)
PASS

Process finished with the exit code 0
```

### CODE REVIEW

File: opentelekomcloud/services/as/resource_opentelekomcloud_as_configuration_v1.go [hunk 1]
```diff
@@ -65,9 +65,10 @@ func ResourceASConfiguration() *schema.Resource {
 							Required: true,
 						},
 						"user_data": {
-							Type:     schema.TypeString,
-							Optional: true,
-							ForceNew: true,
+							Type:             schema.TypeString,
+							Optional:         true,
+							ForceNew:         true,
+							DiffSuppressFunc: common.SuppressEmptyLineSHA,
```
Comment (outcatcher) [inline opentelekomcloud/services/as/resource_opentelekomcloud_as_configuration_v1.go]: It's more like "empty string", than "empty line"

**Review by outcatcher — CHANGES_REQUESTED** [review]

File: opentelekomcloud/services/as/resource_opentelekomcloud_as_configuration_v1.go (hunk 1 above)
Comment (lego963) [reply opentelekomcloud/services/as/resource_opentelekomcloud_as_configuration_v1.go]: done

**Review by outcatcher — APPROVED** [review]

**Review by anton-sidelnikov — APPROVED** [review]
