### PR TITLE
[CCE] Resource opentelekomcloud_cce_node_pool_v3

### LINKED ISSUE #806: [CCE] resource opentelekomcloud_cce_node_pool_v3
# Description of the new resource/data-source
Having the node pools for CCE in Terraform would help us a lot.

I started to write the resource but `make test` is failing and - not being into Go that much - cannot find the issue.

My fork is [here](https://github.com/philippeckel/terraform-provider-opentelekomcloud) and the test fails with

```golang
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
echo $(go list ./... |grep -v 'vendor') | \
        xargs -t -n4 go test  -timeout=30s -parallel=4
go test '-timeout=30s' '-parallel=4' github.com/opentelekomcloud/terraform-provider-opentelekomcloud github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud 
?       github.com/opentelekomcloud/terraform-provider-opentelekomcloud [no test files]
# github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud [github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud.test]
opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3_test.go:140:29: cannot use rName (type string) as type *testing.T in argument to TestAccCCEClusterV3_basic
opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3_test.go:140:29: TestAccCCEClusterV3_basic(rName) used as value
FAIL    github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud [build failed]
FAIL
make: *** [GNUmakefile:13: test] Error 123
```

### PR DESCRIPTION
**Pull request by anton-sidelnikov**
## Summary of the Pull Request
Resolve #806
Based on #807 

Co-authored-by: Philipp Eckel <philipp.eckel@coyoapp.com>

## PR Checklist

* [x] Refers to: #806, #807
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed

```
=== RUN   TestAccCCENodePoolsV3_basic
--- PASS: TestAccCCENodePoolsV3_basic (924.48s)
PASS

Process finished with exit code 0
```

### CODE REVIEW

File: opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go [hunk 1]
```diff
@@ -0,0 +1,542 @@
...
+					Schema: map[string]*schema.Schema{
+						"size": {
+							Type:         schema.TypeInt,
+							Required:     true,
+							ValidateFunc: validation.IntBetween(100, 32768),
+						},
+						"volumetype": {
+							Type:     schema.TypeString,
+							Required: true,
+							ValidateFunc: validation.StringInSlice([]string{
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go]: Maybe it makes sense to use 
```go
CustomizeDiff: multipleCustomizeDiffs(
			validateVolumeType("root_volume.*.volumetype"),
			validateVolumeType("data_volumes.*.volumetype"),
		),
```

To additionally validate used volume types

File: opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go [hunk 2]
```diff
@@ -0,0 +1,542 @@
...
+	if v, ok := d.GetOk("preinstall"); ok {
+		base64PreInstall = installScriptEncode(v.(string))
+	}
+	if v, ok := d.GetOk("postinstall"); ok {
+		base64PostInstall = installScriptEncode(v.(string))
+	}
+	var loginSpec nodes.LoginSpec
+	if hasFilledOpt(d, "key_pair") {
+		loginSpec = nodes.LoginSpec{SshKey: d.Get("key_pair").(string)}
+	} else if hasFilledOpt(d, "password") {
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go]: Why `else` is needed?

File: opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go [hunk 3]
```diff
@@ -0,0 +1,542 @@
...
+		if _, ok := err.(golangsdk.ErrDefault404); ok {
+			d.SetId("")
+			return nil
+		}
+
+		return fmt.Errorf("error retrieving Open Telekom Cloud Node Pool: %s", err)
+	}
+
+	me := &multierror.Error{}
+	me = multierror.Append(me,
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go]: This can be simplified to `me := multierror.Append(...`

File: opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go [hunk 4]
```diff
@@ -0,0 +1,542 @@
...
+							Required: true,
+						},
+						"value": {
+							Type:     schema.TypeString,
+							Required: true,
+						},
+						"effect": {
+							Type:     schema.TypeString,
+							Required: true,
+						},
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go]: Please add validations mentioned in the documentation

File: opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go [hunk 5]
```diff
@@ -0,0 +1,542 @@
...
+func resourceCCENodePoolV3() *schema.Resource {
+	return &schema.Resource{
+		Create: resourceCCENodePoolV3Create,
+		Read:   resourceCCENodePoolV3Read,
+		Update: resourceCCENodePoolV3Update,
+		Delete: resourceCCENodePoolV3Delete,
+
+		Timeouts: &schema.ResourceTimeout{
+			Create: schema.DefaultTimeout(20 * time.Minute),
+			Delete: schema.DefaultTimeout(20 * time.Minute),
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go:35]: Should there also be an `Update` timeout?

File: opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go [hunk 6]
```diff
@@ -0,0 +1,542 @@
...
+				Optional:     true,
+				ForceNew:     true,
+				Sensitive:    true,
+				ExactlyOneOf: []string{"password", "key_pair"},
+			},
+			"subnet_id": {
+				Type:     schema.TypeString,
+				Optional: true,
+				ForceNew: true,
+			},
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go:178]: You can add diff-time validation similar to `validateVPC`

File: opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go [hunk 7]
```diff
@@ -0,0 +1,542 @@
...
+				Optional: true,
+				ForceNew: true,
+				StateFunc: func(v interface{}) string {
+					switch v.(type) {
+					case string:
+						return installScriptHashSum(v.(string))
+					default:
+						return ""
+					}
+				},
```
Comment (outcatcher) [inline opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go]: This part is duplicating multiple times. Can you please move it to a function?

**Review by outcatcher — CHANGES_REQUESTED** [review]

File: opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go [hunk 8]
```diff
@@ -0,0 +1,542 @@
...
+	if err != nil {
+		if _, ok := err.(golangsdk.ErrDefault404); ok {
+			d.SetId("")
+			return nil
+		}
+
+		return fmt.Errorf("error retrieving Open Telekom Cloud Node Pool: %s", err)
+	}
+
+	me := &multierror.Error{}
```
Comment (lego963) [inline opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go]: you can remove initialization and replace with
```go
me := multierror.Append(nil,
		d.Set("name", s.Metadata.Name),
		...
```

**Review by lego963 — CHANGES_REQUESTED** [review]

File: opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go (hunk 2 above)
Comment (anton-sidelnikov) [reply opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go]: because user can use password?

Comment (outcatcher) [reply opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go]: I mean, you can use `if` here without `else`

File: opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go (hunk 8 above)
Comment (outcatcher) [reply opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go]: Even `nil` is not required

**Review by outcatcher — DISMISSED** [review]

**Review by outcatcher — APPROVED** [review]

**Review by lego963 — APPROVED** [review]

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck
